Write a Python program to convert an array to an ordinary list with the same items.

we can use the np.tolist() function

In [15]:

import numpy as np
array1 = np.array([1, 2, 3])
print('NumPy Array:\n',array1)
list1 = array1.tolist()
print('list:\n',list1)

NumPy Array:
 [1 2 3]
list:
 [1, 2, 3]


Write a NumPy program to compute the sum of the diagonal elements of a given array.

Hint: Two methods to solve this problem: 1. manually(without direct function). 2. using the trace function

In [18]:

array1 = np.array([[55, 25, 15],
                    [30, 44, 2],
                    [11, 45, 77]])
  

print("Numpy Matrix is:")
print(array1)
  

trace = np.trace(array1)
  
  
print("\nTrace of given 3X3 matrix:")
print(trace)

Numpy Matrix is:
[[55 25 15]
 [30 44  2]
 [11 45 77]]

Trace of given 3X3 matrix:
176


Given an array of your choice, get all the values higher than X :

if a = [[1,2],[3,5]] and x = 2 :  then 3 and 5 are higher than 2. 



In [19]:
import numpy as np
x = np.array([[0, 10, 20], [20, 30, 40]])
print("Original array: ")
print(x)
print("Values bigger than 10 =", x[x>10])


Original array: 
[[ 0 10 20]
 [20 30 40]]
Values bigger than 10 = [20 20 30 40]


Given two arrays, A & B have the same shape. 

The task is to apply addition by hand: C is the new array. 


In [28]:
import numpy as np
A=np.array([[1,2],[3,4]])
B=np.array([[5,6],[7,8]])
print(A)
print(B)
C=np.add(A, B)
print(C)

[[1 2]
 [3 4]]
[[5 6]
 [7 8]]
[[ 6  8]
 [10 12]]


Write a NumPy program to subtract the mean of each row of a given matrix.

Hint: use the mean function

In [36]:
import numpy as np
a = np.random.random((3, 4))
print(a)
b = a - a.mean(axis=1, keepdims=True)
print(b)

[[0.16218914 0.22702459 0.27875312 0.40078675]
 [0.54803066 0.51759213 0.44177016 0.45102754]
 [0.81593278 0.53357755 0.59375158 0.30131339]]
[[-0.10499926 -0.04016381  0.01156472  0.13359836]
 [ 0.05842554  0.02798701 -0.04783497 -0.03857758]
 [ 0.25478895 -0.02756628  0.03260776 -0.25983043]]
